name: Build Jukebox image
on: [push, workflow_dispatch]
jobs:
  jukebox:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Build shairport-sync
        run: |
            make shairport-sync/shairport-sync.tar
      - name: Upload shairport-sync
        uses: actions/upload-artifact@v3
        with:
          name: shairport-sync
          path: shairport-sync/shairport-sync.tar
      - name: Build raspbian image
        run: |
            make raspbian/image.zip
      - name: Upload raspbian
        uses: actions/upload-artifact@v3
        with:
          name: raspbian
          path: raspbian/image.zip
