name: Release
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download raspbian
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: jukebox.yml
          workflow_conclusion: success
          branch: main
          name: raspbian
          check_artifacts:  true
          search_artifacts: true
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: image.zip
